### ISSUE TITLE
Can not install lib on windows

### ISSUE THREAD

**Issue by XudongLiu** [jwcalder/GraphLearning#11]
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for graphlearning
Failed to build graphlearning
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (graphlearning)

I have update my toolchain, how to sovle

**Comment by jwcalder** [comment]
Hi Xudong,

Thanks for pointing this out. It seems the package is failing to compile in windows for python >= 3.9. Seems like a rather recent issue. I will try to fix this soon. In the meantime, try installing the 1.6.0 version 

https://pypi.org/project/graphlearning/1.6.0/#files

This one compiled fine and if you "pip install graphlearning==1.6.0" you should get the precompiled binaries for windows.

Best,
Jeff

**Comment by jwcalder** [comment]
This should be fixed now. If you install the latest version 1.6.7 it should compile fine in windows. There was a curious conflict with the <complex.h> header file concerning the variable I in my c code, which conflicts with an imaginary number. It is only an issue in Windows, and only very recently. Thanks for noticing, and let me know if you still have trouble.

**Comment by XudongLiu** [comment]
Thank you. I fixed now.
