### ISSUE TITLE
utils.label_to_onehot potentially break

### ISSUE THREAD

**Issue by shwangtangjun** [jwcalder/GraphLearning#12]
During my experiment using `multiclass_mbo` model, I accidentally meet mistake
`operands could not be broadcast together with shapes (9,70000) (10,70000) `

It seems that 10 classes somewhat become 9 classes. After careful investigation, I find out that the error has little to do with `multiclass_mbo` model. Rather, it is `label_to_onehot` that causes the size of variable u to change from  (10,70000)  to (9,70000)
https://github.com/jwcalder/GraphLearning/blob/29b7b5425e6caa66773562783a058bf51c540b57/graphlearning/ssl.py#L996

After manually assigning k=10, instead of deciding the class number based on label maximum as
https://github.com/jwcalder/GraphLearning/blob/29b7b5425e6caa66773562783a058bf51c540b57/graphlearning/utils.py#L564

The error disappears. I think `label_to_onehot` should avoid such situation, where no predictions is class 9 and consequently `np.max(labels)<9`. 

Do you have any opinion on this? I'm not sure if this mistake is uniquely related to `multiclass_mbo` because of the projection step, or if other methods may have a similar issue.

**Comment by jwcalder** [comment]
I agree that labels_to_onehot should take k as input instead of trying to infer it. If the last class disappears it will cause a problem like you noticed. I updated the package to work this way. Can you check to see that this issue is now addressed for you? Update to version 1.6.8.

**Comment by shwangtangjun** [comment]
Works fine for me!
